apiVersion: apps/v1
kind: Deployment
metadata:
  name: rsession-testing-{{ default "node" .Values.kubernetes.node }}
  namespace: rstudio
  labels:
    app: rsession-testing-{{ default "node" .Values.kubernetes.node }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rsession-testing-{{ default "node" .Values.kubernetes.node }}
      tier: backend
  template:
    metadata:
      annotations:
        releaseTime: {{ dateInZone "2006-01-02 15:04:05Z" (now) "UTC"| quote }}
      labels:
        app: rsession-testing-{{ default "node" .Values.kubernetes.node }}
        tier: backend
    spec:
      dnsPolicy: Default
      dnsConfig:
        searches:
          - cs.calvin.edu
      # Allow non-root user to access PersistentVolume
      securityContext:
        fsGroup: 1000
      nodeName: {{ .Values.kubernetes.node }}
      containers:
      - name: rsession-testing-{{ randAlphaNum 24 | nospace | lower }}
        command: ['/usr/bin/sleep','10']
        image: {{ .Values.image.registry }}/{{ .Values.image.name }}:{{ default "latest" .Values.image.tag }}
        #        resources:
        #  requests:
        #    memory: "50Mi"
        #    cpu: "150m" #0.15 CPU
        #  limits:
        #    memory: "100Mi"
        #    cpu: "350m" #0.35 CPU
        
---
