name: Build and push the latest build to staging

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_push_image:
    # runs-on: ubuntu-20.04
    runs-on: arc-runners-infrastructure
    #container: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_NAME }}
          username: ${{ secrets.ACR_LOGIN }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push staging images
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: ${{secrets.ACR_NAME}}/rsession-base:latest
          push: true
          secrets: |
            LDAP_BIND_USER=${{ secrets.LDAP_BIND_USER }}
            LDAP_BIND_PASSWORD=${{ secrets.LDAP_BIND_PASSWORD }}
            DEFAULT_DOMAIN_SID=${{ secrets.DEFAULT_DOMAIN_SID }}
